version: "3"

services:
    express_backend:
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: bidcast
            POSTGRES_HOST: db
        depends_on:
            - db
        links:
            - "db:db"
        build:
            context: ./
            dockerfile: ./backend/Dockerfile
        image: "express_backend:latest"
        ports:
            - "8080:8080"
    db:
        image: "postgres:14"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: bidcast
            POSTGRES_HOST: db
        ports:
            - "8432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
